### ISSUE TITLE
Interface

### ISSUE THREAD

**Issue by inishchith** [email-frappejs/accounting#2]
- [x] Email has `sync` & `send` buttons . 
- [x] list view of received emails 
- [x] Incorp. functions receive and compose
- [ ] set default feilds from DB

**Comment by inishchith** [comment]
@accakks `save` button has to work like `send` .NO insertion to DB , straight in action . UPDATE

**Comment by accakks** [comment]
So sent messages should not be saved?

**Comment by inishchith** [comment]
Yes .

**Comment by inishchith** [comment]
#14
